config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :distributions

  resources :inserts

  resources :insert_pubs

  resources :insert_psresponses

  resources :insert_pspostresponses

  resources :insert_printmethods

  resources :insert_conditions
  
  resources :searches
  
  resources :distributions
  
  resources :p2tests
 

end

app/models/insert.rb
class Insert < ActiveRecord::Base
has_many :insert_psresponses
has_many :insert_pspostresponses, through: :insert_psresponses
end

app/controllers/inserts_controller.rb
class InsertsController < ApplicationController
  before_action :set_insert, only: [:show, :edit, :update, :destroy]

  
  def index
  #params.inspect
  if params[:username].present? 
	@users = User.where('username = ?', params[:username])
  else
	@users = User.limit(1)
  end  
  
    @username = params['username']
    @printsitename = params['printsitename']
	@printsitecode = params['printsitecode']
	
	# convert strings to dates and the date format to yyyy-mm-dd
    if params[:search].present? && params[:txtFromDate].present? && params[:txtToDate].present?	  
      params[:txtFromDate] = Date.strptime(params[:txtFromDate], '%m/%d/%Y').strftime('%Y-%m-%d')
	  params[:txtToDate] = Date.strptime(params[:txtToDate], '%m/%d/%Y').strftime('%Y-%m-%d')
      #params[:txtFromDate] = Date.strptime(params[:txtFromDate], '%m/%d/%Y')
	  #params[:txtToDate] = Date.strptime(params[:txtToDate], '%m/%d/%Y')	  
    end
	
	#select inserts by pub and issue dates
    
    if params[:search].present? && params[:txtFromDate].present? && params[:txtToDate].present? 
	   @inserts = Insert.where('pubcode = ? and issuedate between ? and ? and printsiteready = ?', params[:search], params[:txtFromDate], params[:txtToDate], 'Y') 
    #if params[:search].present? && params[:issuedate1].present? && params[:issuedate2].present?
	  #@inserts = Insert.where('pubcode = ? and issuedate between ? and ?', params[:search], params[:issuedate1], params[:issuedate2])	  
    else	
      @inserts = Insert.limit(3)
    end 
	
	# Display print site name with print site code as parameter
	if params[:distributioncode].present?
	  @distributions = Distribution.where('distribution_code = ?', params[:distributioncode])
	else
      @distributions = Distribution.limit(1)
	end	
	
	if params[:psLookupId].present? && params[:preInsertId].present? 
	@insert_psresponses = InsertPsresponse.where('lookupid = ? and insertid = ?', params[:psLookupId], params[:preInsertId])
    else
      @insert_psresponses = InsertPsresponse.all
	end	
	
	if params[:condID].present?
	@insert_conditions = InsertCondition.where('id = ?', params[:condID])
	else
      @insert_conditions = InsertCondition.limit(1)
	end	
   	  
  end

  # GET /inserts/1
  # sg
  def show
    @inserts = Insert.find(params[:id])
  end

  # GET /inserts/new
  def new
    @insert = Insert.new
  end

  # GET /inserts/1/edit
  # sg
  def edit
    @inserts = Insert.find(params[:id])
  end

  # POST /inserts
  # POST /inserts.json
  def create
    @insert = Insert.new(insert_params)

    respond_to do |format|
      if @insert.save
        format.html { redirect_to @insert, notice: 'Insert was successfully created.' }
        format.json { render :show, status: :created, location: @insert }
      else
        format.html { render :new }
        format.json { render json: @insert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inserts/1
  # PATCH/PUT /inserts/1.json
  def update
    respond_to do |format|
      if @insert.update(insert_params)
        format.html { redirect_to @insert, notice: 'Insert was successfully updated.' }
        format.json { render :show, status: :ok, location: @insert }
      else
        format.html { render :edit }
        format.json { render json: @insert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inserts/1
  # DELETE /inserts/1.json
  def destroy
    @insert.destroy
    respond_to do |format|
      format.html { redirect_to inserts_url, notice: 'Insert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insert
      @insert = Insert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insert_params
      params.require(:insert).permit(:insertid, :inserttypecode, :pubcode, :positioncode, :paperstockid, :methodid, :subtypeid, :createdby, :updatedby, :adstatuscode, :adstatusfursncode, :advacct, :pressrunlonumber, :stagecode, :colorcode, :packagenumber, :issuedate, :productline, :materialdesc, :batchnumber, :width, :height, :pages, :perccircb, :adlinage, :psreceiveddate, :erop, :waitlistheld, :billedby, :eionumber, :cncldbysalesrep, :regional, :cancelledbyuser, :fursndate, :transtimefrom, :transtimeto, :transdateto, :overruns, :insertnotes, :materialinmclean, :exclusive, :schedulernotes, :transdate, :prepressworkid, :weight, :editorialspace, :projruncode, :projdblsect, :straightcollect, :sectionname, :allprintsites, :printsiteready)
    end
end

app/helpers/inserts_helper.rb
module InsertsHelper
end

app/views/inserts/Orig_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inserts</h1>

<table>
  <thead>
    <tr>
      <th>Insertid</th>
      <th>Inserttypecode</th>
      <th>Pubcode</th>
      <th>Positioncode</th>
      <th>Paperstockid</th>
      <th>Methodid</th>
      <th>Subtypeid</th>
      <th>Createdby</th>
      <th>Updatedby</th>
      <th>Adstatuscode</th>
      <th>Adstatusfursncode</th>
      <th>Advacct</th>
      <th>Pressrunlonumber</th>
      <th>Stagecode</th>
      <th>Colorcode</th>
      <th>Packagenumber</th>
      <th>Issuedate</th>
      <th>Productline</th>
      <th>Materialdesc</th>
      <th>Batchnumber</th>
      <th>Width</th>
      <th>Height</th>
      <th>Pages</th>
      <th>Perccircb</th>
      <th>Adlinage</th>
      <th>Psreceiveddate</th>
      <th>Erop</th>
      <th>Waitlistheld</th>
      <th>Billedby</th>
      <th>Eionumber</th>
      <th>Cncldbysalesrep</th>
      <th>Regional</th>
      <th>Cancelledbyuser</th>
      <th>Fursndate</th>
      <th>Transtimefrom</th>
      <th>Transtimeto</th>
      <th>Transdateto</th>
      <th>Overruns</th>
      <th>Insertnotes</th>
      <th>Materialinmclean</th>
      <th>Exclusive</th>
      <th>Schedulernotes</th>
      <th>Transdate</th>
      <th>Prepressworkid</th>
      <th>Weight</th>
      <th>Editorialspace</th>
      <th>Projruncode</th>
      <th>Projdblsect</th>
      <th>Straightcollect</th>
      <th>Sectionname</th>
      <th>Allprintsites</th>
      <th>Printsiteready</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inserts.each do |insert| %>
      <tr>
        <td><%= insert.insertid %></td>
        <td><%= insert.inserttypecode %></td>
        <td><%= insert.pubcode %></td>
        <td><%= insert.positioncode %></td>
        <td><%= insert.paperstockid %></td>
        <td><%= insert.methodid %></td>
        <td><%= insert.subtypeid %></td>
        <td><%= insert.createdby %></td>
        <td><%= insert.updatedby %></td>
        <td><%= insert.adstatuscode %></td>
        <td><%= insert.adstatusfursncode %></td>
        <td><%= insert.advacct %></td>
        <td><%= insert.pressrunlonumber %></td>
        <td><%= insert.stagecode %></td>
        <td><%= insert.colorcode %></td>
        <td><%= insert.packagenumber %></td>
        <td><%= insert.issuedate %></td>
        <td><%= insert.productline %></td>
        <td><%= insert.materialdesc %></td>
        <td><%= insert.batchnumber %></td>
        <td><%= insert.width %></td>
        <td><%= insert.height %></td>
        <td><%= insert.pages %></td>
        <td><%= insert.perccircb %></td>
        <td><%= insert.adlinage %></td>
        <td><%= insert.psreceiveddate %></td>
        <td><%= insert.erop %></td>
        <td><%= insert.waitlistheld %></td>
        <td><%= insert.billedby %></td>
        <td><%= insert.eionumber %></td>
        <td><%= insert.cncldbysalesrep %></td>
        <td><%= insert.regional %></td>
        <td><%= insert.cancelledbyuser %></td>
        <td><%= insert.fursndate %></td>
        <td><%= insert.transtimefrom %></td>
        <td><%= insert.transtimeto %></td>
        <td><%= insert.transdateto %></td>
        <td><%= insert.overruns %></td>
        <td><%= insert.insertnotes %></td>
        <td><%= insert.materialinmclean %></td>
        <td><%= insert.exclusive %></td>
        <td><%= insert.schedulernotes %></td>
        <td><%= insert.transdate %></td>
        <td><%= insert.prepressworkid %></td>
        <td><%= insert.weight %></td>
        <td><%= insert.editorialspace %></td>
        <td><%= insert.projruncode %></td>
        <td><%= insert.projdblsect %></td>
        <td><%= insert.straightcollect %></td>
        <td><%= insert.sectionname %></td>
        <td><%= insert.allprintsites %></td>
        <td><%= insert.printsiteready %></td>
        <td><%= link_to 'Show', insert %></td>
        <td><%= link_to 'Edit', edit_insert_path(insert) %></td>
        <td><%= link_to 'Destroy', insert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insert', new_insert_path %>

app/views/inserts/edit.html.erb
<h1>Editing Insert</h1>

<%= render 'form' %>

<%= link_to 'Show', @insert %> |
<%= link_to 'Back', inserts_path %>

app/views/inserts/index.html - Copy (2).erb
 
<header style="background: #999999;" >
  <h1 style="color: white">Insert Calendar </h1>
</header>
<br /><br />


    

  <body style="background: #f5f5f5;" ><br /><br />
  <hr size="1" color="lightcoral"/>
  
  
  
 
  
 
    <% @inserts.each do |insert| %>
	
<table >	


	<tr>
       <td></td><td><label>Pubcode:</label></td><td><strong><%= insert.pubcode %></strong></td>
	   <td></td><td></td><td><label>Print Site Received Date:</label></td><td><strong><%= insert.psreceiveddate %></strong></td>
	   <td></td><td><label>Updated:</label></td><td><strong><%= insert.updated_at %></strong></td>
    </tr>
	
	<tr>
       <td></td><td><label>Type:</label></td><td><strong><%= insert.inserttypecode %></strong></td>
    </tr>	 
     
	<tr>
	  <td></td><td><label>Run:</label></td><td><strong><%= insert.issuedate %></strong></td>
	  <td><label>#PP:</label></td><td><strong><%= insert.pages %></strong></td>
	  <td></td><td></td><td><label>Status:</label></td><td><strong><%= insert.adstatuscode %></strong></td>
	</tr>  
	
	<tr>
	  <td></td><td><label>Advertiser:</label></td><td><strong><%= insert.advacct %></strong></td>
	  <td><label>Ad Lineage:</label></td><td><strong><%= insert.adlinage %></strong></td>
	  <td></td><td></td><td><label>EROP:</label></td><td><strong><%= insert.erop %></strong></td>	   
	</tr> 

	<tr>
	  <td></td><td><label>Insert#:</label></td><td><strong><%= insert.insertid %></strong></td>
	  <td><label>Width:</label></td><td><strong><%= insert.width %></strong></td>
	  <td></td><td></td><td><label>Height:</label></td><td><strong><%= insert.height %></strong></td> 	 
	</tr>
	
	<tr>
	  <td></td><td><label>Sites:</label></td><td><label>Print site string goes here...</label></td>	 
	  <td></td><td></td><td></td><td></td><td><label>Weight:</label></td><td><strong><%= insert.weight %></strong></td>	  
	</tr>
	
	<tr>
	  <td></td><td><label>Notes:</label></td><td><strong><%= insert.insertnotes %></strong></td>	   	 
	</tr>
	 
    
	<br /> 
	<tr> 
	
    <td><strong><%= link_to 'Print Site Response', insert, {:style=>'color:#cc0000;', :class => "css_class"} %></strong></td>	
      		 
    </table> 
	  
	<hr size="3" color="grey"/>
    <% end %>
	
</body>
<footer>
  <footer style="background: #808080;">
  <h3 style="color: white" align="right" >2015 Gannett </h3>

</footer>
</footer>

app/views/inserts/index.html - Copy.erb
<p id="notice"><%= notice %></p>

<h1>Insert Calendar</h1>

<table>
  <thead>
    <tr>
      <th>Insertid</th>
      <th>Inserttypecode</th>
      <th>Pubcode</th>      
      <th>Adstatuscode</th>      
      <th>Advacct</th>     
      <th>Issuedate</th>      
      <th>Width</th>
      <th>Height</th>
      <th>Pages</th>      
      <th>Adlinage</th>
      <th>Psreceiveddate</th>
      <th>Erop</th>          
      <th>Insertnotes</th>      
      <th>Exclusive</th>      
      <th>Weight</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inserts.each do |insert| %>	
<p>	
      <tr>	 
        <td><%= insert.insertid %></td>
        <td><%= insert.inserttypecode %></td>
        <td><%= insert.pubcode %></td>        
        <td><%= insert.adstatuscode %></td>        
        <td><%= insert.advacct %></td>        
        <td><%= insert.issuedate %></td> 
		
        <td><%= insert.width %></td>
        <td><%= insert.height %></td>
        <td><%= insert.pages %></td>       
        <td><%= insert.adlinage %></td>
        <td><%= insert.psreceiveddate %></td>
        <td><%= insert.erop %></td>
        <td><%= insert.waitlistheld %></td>        
        <td><%= insert.updated_at %></td>  		
        <td><%= insert.insertnotes %></td>        
        <td><%= insert.weight %></td>        
        <td><%= insert.allprintsites %></td>       		
        <td><%= link_to 'Print Site Response', insert %></td>		
        <td><%= link_to 'Edit', edit_insert_path(insert) %></td>
        <td><%= link_to 'Destroy', insert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		 
      </tr>
	  
	  </p>
	   
    <% end %>
	
  </tbody>
  
</table>

<br>

<%= link_to 'New Insert', new_insert_path %>

app/views/inserts/index.html.erb
 
<header style="background: #999999;" >
  <h1 style="color: white">Insert Calendar </h1>
</header>

<br />

<%= form_tag("/inserts", :method => "get") do %>
<table>
 <tr>
  <td style="text-align:right"><%= label_tag 'Pub:' %></td>
  <!--<%= text_field_tag :search, params[:search] %><br /><br />-->
   
  <td><%= select_tag :search, options_from_collection_for_select(InsertPub.all, :pub_code, :pub_code, params[:search]), include_blank: false %></td>
 </tr>  
<tr>
  <td style="text-align:right"><%= label_tag 'From:' %></td>  
  <td><input type="text", name="txtFromDate", id="txtFromDate" /></td>
  
  <td style="text-align:right"><%= label_tag 'To:' %></td>  
  <td><input type="text", name="txtToDate", id="txtToDate" /></td> 
  
  <!--<td><%= date_field_tag :issuedate1, params[:issuedate1] %></td>-->  
  <!--<td><%= text_field_tag :txtFromDate, params[:txtFromDate] %></td>-->
  <!--<td><%= date_field_tag :issuedate2, params[:issuedate2] %></td>-->  
  <!--<td><%= text_field_tag :txtToDate, params[:txtToDate] %></td>-->
</tr>
<tr>
 <td></td>
 <td> <%= submit_tag "Search", :name => nil %></td>
</tr>  
</table>
<% end %>

<body style="background: #fcfcfc;" ><br />
<hr size="2" color="grey"/><hr size="2" color="grey"/>
   
<% @inserts.each do |insert| %>

<% for distribution in @distributions %>
<% end %>
<% for insert_psresponse in @insert_psresponses %>
<% end %>
<% for insert_condition in @insert_conditions %>
<% end %>

<%= form_tag("/inserts", :method => "get") do %>
<table>
  <tr>    	
	
    <!--<%= text_field_tag :preinsertid, params[:preinsertid] %>-->
	<!--<%= text_field_tag :psLookupid, params[:psLookupid] %>-->
    <!--<%= text_field_tag :condID, params[:condID] %>--> 
	
	<!--<%= text_field_tag "distributioncode", distribution.distribution_code %>-->
	<%= text_field_tag "psLookupId", distribution.lookup_id %>
	<%= text_field_tag "preInsertId", insert.insertid %>	
	
   <!-- insert_psresponse.conditionid is used to retreive the condition name from insert_conditions   -->
    <%= text_field_tag "condID", insert_psresponse.conditionid %>
	
  </tr>
  <tr>
    <td></td>
    <td> <%= submit_tag "GetInsertInfo" %></td>
  </tr>
</table>
<% end %>

	
<table>
  <tr>
	<td></td><td bgcolor="#cdb79e"><strong><%= distribution.description %></strong></td><td></td><td style="color:blue"><strong><%= insert_condition.conditionname %></strong></td>	
  </tr>
  
  <tr>	   
       <td></td><td><label>Pubcode:</label></td><td><strong><%= insert.pubcode %></strong></td>
	   <td></td><td></td><td><label>Print Site Received Date:</label></td><td><strong><%= insert.psreceiveddate %></strong></td>
	   <td></td><td><label>Updated:</label></td><td><strong><%= insert.updated_at %></strong></td>
    </tr>
	
	<tr>
       <td></td><td><label>Type:</label></td><td><strong><%= insert.inserttypecode %></strong></td>
    </tr>	 
     
	<tr>
	  <td></td><td><label>Run:</label></td><td><strong><%= insert.issuedate %></strong></td>
	  <td><label>#PP:</label></td><td><strong><%= insert.pages %></strong></td>
	  <td></td><td></td><td><label>Status:</label></td><td><strong><%= insert.adstatuscode %></strong></td>
	</tr>  
	
	<tr>
	  <td></td><td><label>Advertiser:</label></td><td><strong><%= insert.advacct %></strong></td>
	  <td><label>Ad Lineage:</label></td><td><strong><%= insert.adlinage %></strong></td>
	  <td></td><td></td><td><label>EROP:</label></td><td><strong><%= insert.erop %></strong></td>	   
	</tr> 

	<tr>
	  <td></td><td><label>Insert#:</label></td><td><strong><%= insert.insertid %></strong></td>
	  <td><label>Width:</label></td><td><strong><%= insert.width %></strong></td>
	  <td></td><td></td><td><label>Height:</label></td><td><strong><%= insert.height %></strong></td> 	 
	</tr>
	
	<tr>
	  <td></td><td><label>Sites:</label></td><td><label>Print site string goes here...</label></td>	 
	  <td></td><td></td><td></td><td></td><td><label>Weight:</label></td><td><strong><%= insert.weight %></strong></td>	  
	</tr>
	
	<tr>
	  <td></td><td><label>Notes:</label></td><td><strong><%= insert.insertnotes %></strong></td>	   	 
	</tr>
    
	 
	<tr> 
	<% if insert.inserttypecode == "FSI" || insert.inserttypecode == "PROMO" || insert.inserttypecode == "SASI" %>
      <td><p style="text-align:left;font-size:110%"><strong><%= link_to 'Print Site Response', insert_psresponses_path(:InsertID => insert.insertid, :IssueDate => insert.issuedate, :Printsite => distribution.description, :Inserttype => insert.inserttypecode, :condName => insert_condition.conditionname ,:Advertiser => insert.advacct), {:style=>'color:#990033;', :class => "css_class"} %></strong></td>
    <% end %>

    </table> 
	  
	<hr size="3" color="grey"/>
    <% end %>
	
</body>
<footer>
  <footer style="background: #808080;">
  <h3 style="color: white" align="right" >2015 Gannett </h3>

</footer>

app/views/inserts/new.html.erb
<h1>New Insert</h1>

<%= render 'form' %>

<%= link_to 'Back', inserts_path %>

app/views/inserts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>  Circ Response Data goes here... </h1>
<p>
  <strong>Insertid:</strong>
  <%= @insert.insertid %>
</p>

<p>
  <strong>Inserttypecode:</strong>
  <%= @insert.inserttypecode %>
</p>

<p>
  <strong>Pubcode:</strong>
  <%= @insert.pubcode %>
</p>

<p>
  <strong>Positioncode:</strong>
  <%= @insert.positioncode %>
</p>

<p>
  <strong>Paperstockid:</strong>
  <%= @insert.paperstockid %>
</p>

<p>
  <strong>Methodid:</strong>
  <%= @insert.methodid %>
</p>

<p>
  <strong>Subtypeid:</strong>
  <%= @insert.subtypeid %>
</p>

<p>
  <strong>Createdby:</strong>
  <%= @insert.createdby %>
</p>

<p>
  <strong>Updatedby:</strong>
  <%= @insert.updatedby %>
</p>

<p>
  <strong>Adstatuscode:</strong>
  <%= @insert.adstatuscode %>
</p>

<p>
  <strong>Adstatusfursncode:</strong>
  <%= @insert.adstatusfursncode %>
</p>

<p>
  <strong>Advacct:</strong>
  <%= @insert.advacct %>
</p>

<p>
  <strong>Pressrunlonumber:</strong>
  <%= @insert.pressrunlonumber %>
</p>

<p>
  <strong>Stagecode:</strong>
  <%= @insert.stagecode %>
</p>

<p>
  <strong>Colorcode:</strong>
  <%= @insert.colorcode %>
</p>

<p>
  <strong>Packagenumber:</strong>
  <%= @insert.packagenumber %>
</p>

<p>
  <strong>Issuedate:</strong>
  <%= @insert.issuedate %>
</p>

<p>
  <strong>Productline:</strong>
  <%= @insert.productline %>
</p>

<p>
  <strong>Materialdesc:</strong>
  <%= @insert.materialdesc %>
</p>

<p>
  <strong>Batchnumber:</strong>
  <%= @insert.batchnumber %>
</p>

<p>
  <strong>Width:</strong>
  <%= @insert.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @insert.height %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @insert.pages %>
</p>

<p>
  <strong>Perccircb:</strong>
  <%= @insert.perccircb %>
</p>

<p>
  <strong>Adlinage:</strong>
  <%= @insert.adlinage %>
</p>

<p>
  <strong>Psreceiveddate:</strong>
  <%= @insert.psreceiveddate %>
</p>

<p>
  <strong>Erop:</strong>
  <%= @insert.erop %>
</p>

<p>
  <strong>Waitlistheld:</strong>
  <%= @insert.waitlistheld %>
</p>

<p>
  <strong>Billedby:</strong>
  <%= @insert.billedby %>
</p>

<p>
  <strong>Eionumber:</strong>
  <%= @insert.eionumber %>
</p>

<p>
  <strong>Cncldbysalesrep:</strong>
  <%= @insert.cncldbysalesrep %>
</p>

<p>
  <strong>Regional:</strong>
  <%= @insert.regional %>
</p>

<p>
  <strong>Cancelledbyuser:</strong>
  <%= @insert.cancelledbyuser %>
</p>

<p>
  <strong>Fursndate:</strong>
  <%= @insert.fursndate %>
</p>

<p>
  <strong>Transtimefrom:</strong>
  <%= @insert.transtimefrom %>
</p>

<p>
  <strong>Transtimeto:</strong>
  <%= @insert.transtimeto %>
</p>

<p>
  <strong>Transdateto:</strong>
  <%= @insert.transdateto %>
</p>

<p>
  <strong>Overruns:</strong>
  <%= @insert.overruns %>
</p>

<p>
  <strong>Insertnotes:</strong>
  <%= @insert.insertnotes %>
</p>

<p>
  <strong>Materialinmclean:</strong>
  <%= @insert.materialinmclean %>
</p>

<p>
  <strong>Exclusive:</strong>
  <%= @insert.exclusive %>
</p>

<p>
  <strong>Schedulernotes:</strong>
  <%= @insert.schedulernotes %>
</p>

<p>
  <strong>Transdate:</strong>
  <%= @insert.transdate %>
</p>

<p>
  <strong>Prepressworkid:</strong>
  <%= @insert.prepressworkid %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @insert.weight %>
</p>

<p>
  <strong>Editorialspace:</strong>
  <%= @insert.editorialspace %>
</p>

<p>
  <strong>Projruncode:</strong>
  <%= @insert.projruncode %>
</p>

<p>
  <strong>Projdblsect:</strong>
  <%= @insert.projdblsect %>
</p>

<p>
  <strong>Straightcollect:</strong>
  <%= @insert.straightcollect %>
</p>

<p>
  <strong>Sectionname:</strong>
  <%= @insert.sectionname %>
</p>

<p>
  <strong>Allprintsites:</strong>
  <%= @insert.allprintsites %>
</p>

<p>
  <strong>Printsiteready:</strong>
  <%= @insert.printsiteready %>
</p>

<%= link_to 'Edit', edit_insert_path(@insert) %> |
<%= link_to 'Back', inserts_path %>