config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :distributions

  resources :inserts

  resources :insert_pubs

  resources :insert_psresponses

  resources :insert_pspostresponses

  resources :insert_printmethods

  resources :insert_conditions
  
  resources :searches
  
  resources :distributions
  
  resources :p2tests
 

end

app/models/distribution.rb
class Distribution < ActiveRecord::Base
end

app/controllers/distributions_controller.rb
class DistributionsController < ApplicationController
  before_action :set_distribution, only: [:show, :edit, :update, :destroy]

  # GET /distributions
  # GET /distributions.json
  def index
    @distributions = Distribution.all
  end

  # GET /distributions/1
  # GET /distributions/1.json
  def show
  end

  # GET /distributions/new
  def new
    @distribution = Distribution.new
  end

  # GET /distributions/1/edit
  def edit
  end

  # POST /distributions
  # POST /distributions.json
  def create
    @distribution = Distribution.new(distribution_params)

    respond_to do |format|
      if @distribution.save
        format.html { redirect_to @distribution, notice: 'Distribution was successfully created.' }
        format.json { render :show, status: :created, location: @distribution }
      else
        format.html { render :new }
        format.json { render json: @distribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distributions/1
  # PATCH/PUT /distributions/1.json
  def update
    respond_to do |format|
      if @distribution.update(distribution_params)
        format.html { redirect_to @distribution, notice: 'Distribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @distribution }
      else
        format.html { render :edit }
        format.json { render json: @distribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distributions/1
  # DELETE /distributions/1.json
  def destroy
    @distribution.destroy
    respond_to do |format|
      format.html { redirect_to distributions_url, notice: 'Distribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distribution
      @distribution = Distribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distribution_params
      params.require(:distribution).permit(:lookup_id, :level_number, :distribution_code, :description, :newspaper_name, :parent_lookup_id, :sort, :text_active, :active_date, :inactive_date, :pub_id, :parent_id, :acitve, :created_at, :updated_at, :created_by, :updated_by, :address)
    end
end

app/helpers/distributions_helper.rb
module DistributionsHelper
end

app/views/distributions/_form.html.erb
<%= form_for(@distribution) do |f| %>
  <% if @distribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@distribution.errors.count, "error") %> prohibited this distribution from being saved:</h2>

      <ul>
      <% @distribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lookup_id %><br>
    <%= f.number_field :lookup_id %>
  </div>
  <div class="field">
    <%= f.label :level_number %><br>
    <%= f.number_field :level_number %>
  </div>
  <div class="field">
    <%= f.label :distribution_code %><br>
    <%= f.text_field :distribution_code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :newspaper_name %><br>
    <%= f.text_field :newspaper_name %>
  </div>
  <div class="field">
    <%= f.label :parent_lookup_id %><br>
    <%= f.number_field :parent_lookup_id %>
  </div>
  <div class="field">
    <%= f.label :sort %><br>
    <%= f.text_field :sort %>
  </div>
  <div class="field">
    <%= f.label :text_active %><br>
    <%= f.text_field :text_active %>
  </div>
  <div class="field">
    <%= f.label :active_date %><br>
    <%= f.date_select :active_date %>
  </div>
  <div class="field">
    <%= f.label :inactive_date %><br>
    <%= f.date_select :inactive_date %>
  </div>
  <div class="field">
    <%= f.label :pub_id %><br>
    <%= f.number_field :pub_id %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :acitve %><br>
    <%= f.number_field :acitve %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br>
    <%= f.text_field :updated_by %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/distributions/edit.html.erb
<h1>Editing Distribution</h1>

<%= render 'form' %>

<%= link_to 'Show', @distribution %> |
<%= link_to 'Back', distributions_path %>

app/views/distributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Distributions</h1>

<table>
  <thead>
    <tr>
      <th>Lookup</th>
      <th>Level number</th>
      <th>Distribution code</th>
      <th>Description</th>
      <th>Newspaper name</th>
      <th>Parent lookup</th>
      <th>Sort</th>
      <th>Text active</th>
      <th>Active date</th>
      <th>Inactive date</th>
      <th>Pub</th>
      <th>Parent</th>
      <th>Acitve</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distributions.each do |distribution| %>
      <tr>
        <td><%= distribution.lookup_id %></td>
        <td><%= distribution.level_number %></td>
        <td><%= distribution.distribution_code %></td>
        <td><%= distribution.description %></td>
        <td><%= distribution.newspaper_name %></td>
        <td><%= distribution.parent_lookup_id %></td>
        <td><%= distribution.sort %></td>
        <td><%= distribution.text_active %></td>
        <td><%= distribution.active_date %></td>
        <td><%= distribution.inactive_date %></td>
        <td><%= distribution.pub_id %></td>
        <td><%= distribution.parent_id %></td>
        <td><%= distribution.acitve %></td>
        <td><%= distribution.created_at %></td>
        <td><%= distribution.updated_at %></td>
        <td><%= distribution.created_by %></td>
        <td><%= distribution.updated_by %></td>
        <td><%= distribution.address %></td>
        <td><%= link_to 'Show', distribution %></td>
        <td><%= link_to 'Edit', edit_distribution_path(distribution) %></td>
        <td><%= link_to 'Destroy', distribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distribution', new_distribution_path %>

app/views/distributions/new.html.erb
<h1>New Distribution</h1>

<%= render 'form' %>

<%= link_to 'Back', distributions_path %>

app/views/distributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lookup:</strong>
  <%= @distribution.lookup_id %>
</p>

<p>
  <strong>Level number:</strong>
  <%= @distribution.level_number %>
</p>

<p>
  <strong>Distribution code:</strong>
  <%= @distribution.distribution_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @distribution.description %>
</p>

<p>
  <strong>Newspaper name:</strong>
  <%= @distribution.newspaper_name %>
</p>

<p>
  <strong>Parent lookup:</strong>
  <%= @distribution.parent_lookup_id %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @distribution.sort %>
</p>

<p>
  <strong>Text active:</strong>
  <%= @distribution.text_active %>
</p>

<p>
  <strong>Active date:</strong>
  <%= @distribution.active_date %>
</p>

<p>
  <strong>Inactive date:</strong>
  <%= @distribution.inactive_date %>
</p>

<p>
  <strong>Pub:</strong>
  <%= @distribution.pub_id %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @distribution.parent_id %>
</p>

<p>
  <strong>Acitve:</strong>
  <%= @distribution.acitve %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @distribution.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @distribution.updated_at %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @distribution.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @distribution.updated_by %>
</p>

<p>
  <strong>Address:</strong>
  <%= @distribution.address %>
</p>

<%= link_to 'Edit', edit_distribution_path(@distribution) %> |
<%= link_to 'Back', distributions_path %>