config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :distributions

  resources :inserts

  resources :insert_pubs

  resources :insert_psresponses

  resources :insert_pspostresponses

  resources :insert_printmethods

  resources :insert_conditions
  
  resources :searches
  
  resources :distributions
  
  resources :p2tests
 

end

app/models/insert_condition.rb
class InsertCondition < ActiveRecord::Base
end

app/controllers/insert_conditions_controller.rb
class InsertConditionsController < ApplicationController
  before_action :set_insert_condition, only: [:show, :edit, :update, :destroy]

  # GET /insert_conditions
  # GET /insert_conditions.json
  def index
    @insert_conditions = InsertCondition.all
  end

  # GET /insert_conditions/1
  # GET /insert_conditions/1.json
  def show
  end

  # GET /insert_conditions/new
  def new
    @insert_condition = InsertCondition.new
  end

  # GET /insert_conditions/1/edit
  def edit
  end

  # POST /insert_conditions
  # POST /insert_conditions.json
  def create
    @insert_condition = InsertCondition.new(insert_condition_params)

    respond_to do |format|
      if @insert_condition.save
        format.html { redirect_to @insert_condition, notice: 'Insert condition was successfully created.' }
        format.json { render :show, status: :created, location: @insert_condition }
      else
        format.html { render :new }
        format.json { render json: @insert_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insert_conditions/1
  # PATCH/PUT /insert_conditions/1.json
  def update
    respond_to do |format|
      if @insert_condition.update(insert_condition_params)
        format.html { redirect_to @insert_condition, notice: 'Insert condition was successfully updated.' }
        format.json { render :show, status: :ok, location: @insert_condition }
      else
        format.html { render :edit }
        format.json { render json: @insert_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insert_conditions/1
  # DELETE /insert_conditions/1.json
  def destroy
    @insert_condition.destroy
    respond_to do |format|
      format.html { redirect_to insert_conditions_url, notice: 'Insert condition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insert_condition
      @insert_condition = InsertCondition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insert_condition_params
      params.require(:insert_condition).permit(:conditionname, :responsecode)
    end
end

app/helpers/insert_conditions_helper.rb
module InsertConditionsHelper
end

app/views/insert_conditions/_form.html.erb
<%= form_for(@insert_condition) do |f| %>
  <% if @insert_condition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insert_condition.errors.count, "error") %> prohibited this insert_condition from being saved:</h2>

      <ul>
      <% @insert_condition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conditionname %><br>
    <%= f.text_field :conditionname %>
  </div>
  <div class="field">
    <%= f.label :responsecode %><br>
    <%= f.text_field :responsecode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insert_conditions/edit.html.erb
<h1>Editing Insert Condition</h1>

<%= render 'form' %>

<%= link_to 'Show', @insert_condition %> |
<%= link_to 'Back', insert_conditions_path %>

app/views/insert_conditions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Insert Conditions</h1>

<table>
  <thead>
    <tr>
      <th>Conditionname</th>
      <th>Responsecode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insert_conditions.each do |insert_condition| %>
      <tr>
        <td><%= insert_condition.conditionname %></td>
        <td><%= insert_condition.responsecode %></td>
        <td><%= link_to 'Show', insert_condition %></td>
        <td><%= link_to 'Edit', edit_insert_condition_path(insert_condition) %></td>
        <td><%= link_to 'Destroy', insert_condition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insert condition', new_insert_condition_path %>

app/views/insert_conditions/new.html.erb
<h1>New Insert Condition</h1>

<%= render 'form' %>

<%= link_to 'Back', insert_conditions_path %>

app/views/insert_conditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conditionname:</strong>
  <%= @insert_condition.conditionname %>
</p>

<p>
  <strong>Responsecode:</strong>
  <%= @insert_condition.responsecode %>
</p>

<%= link_to 'Edit', edit_insert_condition_path(@insert_condition) %> |
<%= link_to 'Back', insert_conditions_path %>