config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :distributions

  resources :inserts

  resources :insert_pubs

  resources :insert_psresponses

  resources :insert_pspostresponses

  resources :insert_printmethods

  resources :insert_conditions
  
  resources :searches
  
  resources :distributions
  
  resources :p2tests
 

end

app/models/insert_printmethod.rb
class InsertPrintmethod < ActiveRecord::Base
end

app/controllers/insert_printmethods_controller.rb
class InsertPrintmethodsController < ApplicationController
  before_action :set_insert_printmethod, only: [:show, :edit, :update, :destroy]

  # GET /insert_printmethods
  # GET /insert_printmethods.json
  def index
    @insert_printmethods = InsertPrintmethod.all
  end

  # GET /insert_printmethods/1
  # GET /insert_printmethods/1.json
  def show
  end

  # GET /insert_printmethods/new
  def new
    @insert_printmethod = InsertPrintmethod.new
  end

  # GET /insert_printmethods/1/edit
  def edit
  end

  # POST /insert_printmethods
  # POST /insert_printmethods.json
  def create
    @insert_printmethod = InsertPrintmethod.new(insert_printmethod_params)

    respond_to do |format|
      if @insert_printmethod.save
        format.html { redirect_to @insert_printmethod, notice: 'Insert printmethod was successfully created.' }
        format.json { render :show, status: :created, location: @insert_printmethod }
      else
        format.html { render :new }
        format.json { render json: @insert_printmethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insert_printmethods/1
  # PATCH/PUT /insert_printmethods/1.json
  def update
    respond_to do |format|
      if @insert_printmethod.update(insert_printmethod_params)
        format.html { redirect_to @insert_printmethod, notice: 'Insert printmethod was successfully updated.' }
        format.json { render :show, status: :ok, location: @insert_printmethod }
      else
        format.html { render :edit }
        format.json { render json: @insert_printmethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insert_printmethods/1
  # DELETE /insert_printmethods/1.json
  def destroy
    @insert_printmethod.destroy
    respond_to do |format|
      format.html { redirect_to insert_printmethods_url, notice: 'Insert printmethod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insert_printmethod
      @insert_printmethod = InsertPrintmethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insert_printmethod_params
      params.require(:insert_printmethod).permit(:methodname)
    end
end

app/helpers/insert_printmethods_helper.rb
module InsertPrintmethodsHelper
end

app/views/insert_printmethods/_form.html.erb
<%= form_for(@insert_printmethod) do |f| %>
  <% if @insert_printmethod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insert_printmethod.errors.count, "error") %> prohibited this insert_printmethod from being saved:</h2>

      <ul>
      <% @insert_printmethod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :methodname %><br>
    <%= f.text_field :methodname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insert_printmethods/edit.html.erb
<h1>Editing Insert Printmethod</h1>

<%= render 'form' %>

<%= link_to 'Show', @insert_printmethod %> |
<%= link_to 'Back', insert_printmethods_path %>

app/views/insert_printmethods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Insert Printmethods</h1>

<table>
  <thead>
    <tr>
      <th>Methodname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insert_printmethods.each do |insert_printmethod| %>
      <tr>
        <td><%= insert_printmethod.methodname %></td>
        <td><%= link_to 'Show', insert_printmethod %></td>
        <td><%= link_to 'Edit', edit_insert_printmethod_path(insert_printmethod) %></td>
        <td><%= link_to 'Destroy', insert_printmethod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insert printmethod', new_insert_printmethod_path %>

app/views/insert_printmethods/new.html.erb
<h1>New Insert Printmethod</h1>

<%= render 'form' %>

<%= link_to 'Back', insert_printmethods_path %>

app/views/insert_printmethods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Methodname:</strong>
  <%= @insert_printmethod.methodname %>
</p>

<%= link_to 'Edit', edit_insert_printmethod_path(@insert_printmethod) %> |
<%= link_to 'Back', insert_printmethods_path %>